In [1]:
import numpy as np
import pandas as pd
import pickle

In [5]:
test_data = pd.read_csv("data/final_data.csv")

In [2]:
with open ("model_pickle", "rb") as f:
    model = pickle.load(f)

In [6]:
test_data.head()

,SIBS,DEGREE_BACHELOR,DEGREE_GRADUATE,DEGREE_HIGH SCHOOL,DEGREE_JUNIOR COLLEGE,PADEG_BACHELOR,PADEG_GRADUATE,PADEG_HIGH SCHOOL,PADEG_JUNIOR COLLEGE,PADEG_LT HIGH SCHOOL,...,GRANBORN_4.0,GRANBORN_ALL IN U.S,POLVIEWS_CONSERVATIVE,POLVIEWS_EXTREMELY LIBERAL,POLVIEWS_EXTRMLY CONSERVATIVE,POLVIEWS_LIBERAL,POLVIEWS_MODERATE,POLVIEWS_SLGHTLY CONSERVATIVE,POLVIEWS_SLIGHTLY LIBERAL,INCOME
0,1.0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,8000
1,6.0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,7000
2,0.0,0,1,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,50000
3,8.0,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,25000
4,7.0,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,75000

In [9]:
test_data.drop(columns="INCOME", inplace=True)

In [10]:
test_data["INCOME_pred"] = model.predict(test_data)

In [40]:
test_data.head(30)

,SIBS,DEGREE_BACHELOR,DEGREE_GRADUATE,DEGREE_HIGH SCHOOL,DEGREE_JUNIOR COLLEGE,PADEG_BACHELOR,PADEG_GRADUATE,PADEG_HIGH SCHOOL,PADEG_JUNIOR COLLEGE,PADEG_LT HIGH SCHOOL,...,GRANBORN_4.0,GRANBORN_ALL IN U.S,POLVIEWS_CONSERVATIVE,POLVIEWS_EXTREMELY LIBERAL,POLVIEWS_EXTRMLY CONSERVATIVE,POLVIEWS_LIBERAL,POLVIEWS_MODERATE,POLVIEWS_SLGHTLY CONSERVATIVE,POLVIEWS_SLIGHTLY LIBERAL,INCOME_pred
0,1.0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,56379.286790
1,6.0,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,23471.255833
2,0.0,0,1,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,64928.354624
3,8.0,0,0,1,0,0,0,0,0,1,...,0,1,0,0,0,0,1,0,0,34265.740557
4,7.0,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,43338.117607
5,3.0,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,55328.672476
6,2.0,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,33067.664304
7,11.0,0,0,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,1,0,23191.470990
8,2.0,1,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,55014.130147
9,2.0,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,1,0,54821.768222
10,0.0,1,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,34500.620825
11,5.0,1,0,0,0,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,36484.368468
12,2.0,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,53942.061937
13,6.0,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,30471.200943
14,6.0,0,1,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,61889.757681
15,1.0,0,1,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,46526.122896
16,1.0,0,0,0,1,0,0,1,0,0,...,1,0,1,0,0,0,0,0,0,30539.597930
17,1.0,0,0,0,1,0,0,1,0,0,...,1,0,0,0,0,0,0,1,0,41443.831357
18,15.0,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,1,45627.633743
19,3.0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,48617.106698
20,1.0,0,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,41810.022081
21,1.0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,36632.648996
22,2.0,0,0,1,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,44431.627188
23,1.0,0,1,0,0,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,64499.902564
24,4.0,1,0,0,0,0,0,0,0,1,...,0,1,1,0,0,0,0,0,0,35562.839202
25,0.0,0,0,0,1,0,0,1,0,0,...,0,1,1,0,0,0,0,0,0,27897.238933
26,4.0,1,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,1,0,0,33237.130401
27,1.0,1,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,51466.597225
28,3.0,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,1,0,0,67762.431924
29,0.0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,47039.987761

In [56]:
needs = 100000

In [57]:
earns = 64928.354624

In [68]:
years = 10

In [73]:
rate_year = 0.1

In [74]:
absolute = earns*rate_year*years - needs

In [75]:
ROI = absolute/needs

In [76]:
print(ROI * 100)

-35.071645376